In [1]:
import pandas as pd


In [3]:
s = pd.series([1,2,3,4,5])

AttributeError: module 'pandas' has no attribute 'series'

import numpy as np

In [4]:
import numpy as np

In [5]:
pf = pd.DataFrame({
    'name' : ['sanskar','vishal','jyoti'],
    'age' : [10,20,30],
    'city' : ['gaya','patna','bihar']
})
print(pf)

      name  age   city
0  sanskar   10   gaya
1   vishal   20  patna
2    jyoti   30  bihar


In [6]:
print(pf.head())

      name  age   city
0  sanskar   10   gaya
1   vishal   20  patna
2    jyoti   30  bihar


In [7]:
print(pf['name'])

0    sanskar
1     vishal
2      jyoti
Name: name, dtype: object


In [8]:
print(pf['name','age'])

KeyError: ('name', 'age')

In [9]:
print(pf[['name','age']])

      name  age
0  sanskar   10
1   vishal   20
2    jyoti   30


In [11]:
np.random.randint(low=100,high=1000)

476

In [12]:
np.random.randint(low=100,high=1000)
np.seed(23)

AttributeError: module 'numpy' has no attribute 'seed'

In [13]:
np.random.seed(23)

In [16]:
np.random.randint(low=100,high=999)
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [19]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
l1=[1,2,3,4,5,6,7,8,9]
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
l1[1]/10

0.2

In [22]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
arr-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [24]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [25]:
arr[arr>5]

array([6, 7, 8, 9])

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr1=arr[0:6]

In [28]:
arr1

array([0, 1, 2, 3, 4, 5])

In [29]:
arr[:5]

array([0, 1, 2, 3, 4])

In [30]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [32]:
arr1[:]=555

In [33]:
arr1

array([555, 555, 555, 555, 555, 555])

In [34]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

# Copy

In [35]:
arr2= arr.copy()
arr2

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [36]:
arr2[:]=1000
arr2

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [37]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

# Python list vs numpy array

In [38]:
size = 1000
x = range(size)
y = range(size)
x

range(0, 1000)

In [39]:
y

range(0, 1000)

In [40]:
%%limit

UsageError: Cell magic `%%limit` not found.


In [41]:
%%timeit

UsageError: %%timeit is a cell magic, but the cell body is empty. Did you mean the line magic %timeit (single %)?


In [42]:
%%timeit
[x[i]*y[i] for i in range (size)]

207 µs ± 1.67 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [43]:
x1 = np.arange(size)
y1 = np.arange(size)

In [44]:
%%timeit
x1*y1

1.25 µs ± 5.38 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# insert

In [50]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
b1=np.insert(b,1,[15,16,17],axis = 0)
b1

array([[ 1,  2,  3],
       [15, 16, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [53]:
b1 = np.insert(b1,1,[12,13,14,15],axis = 1)
b1

array([[ 1, 12,  2,  3],
       [15, 13, 16, 17],
       [ 4, 14,  5,  6],
       [ 7, 15,  8,  9]])

# matrix

In [54]:
x = np.matrix(b)

In [55]:
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
x[2,1]

8

In [57]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [59]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr[2,1]=-7
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [63]:
np.insert(arr,2,2)

array([ 1,  2,  2,  3,  4,  5,  6,  7, -7,  9])

In [62]:
x*x

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [64]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 49, 81]])

In [65]:
arr@arr

array([[ 30,  -9,  42],
       [ 66,  -9,  96],
       [ 42, -84,  60]])

# storage in a file

In [66]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [67]:
np.savetxt('a.txt',arr)

In [69]:
np.savetxt('a.txt',arr,delimiter=',')

In [71]:
np.loadtxt('a.txt',delimiter=',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., -7.,  9.]])

In [72]:
np.save('date.npy',arr)

In [74]:
np.load('date.npy')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [75]:
a = np.arange(10)

In [76]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.savez('both.npz',arr,a)

In [78]:
z = np.load('date.npy')

In [79]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [80]:
y = np.load('both.npz')

In [81]:
z.files

AttributeError: 'numpy.ndarray' object has no attribute 'files'

In [82]:
y.files

['arr_0', 'arr_1']

In [84]:
y[y.files[0]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [85]:
y[y.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# pandas


In [89]:
import pandas as pd

my_list = [100,200,300,400,500]

In [90]:
x = pd.Series(my_list,index = ['A','B','C','D','E'])
x

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [91]:
type(x)

pandas.core.series.Series

# using numpy array

In [92]:
arr=np.array(my_list)

In [93]:
arr


array([100, 200, 300, 400, 500])

In [96]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [97]:
pd.Series(arr,'A B C D E'.split())

A    100
B    200
C    300
D    400
E    500
dtype: int32

# using dictionaries 

In [102]:
dict1 = {'A':100,'B':200,'C':300}
dict1

{'A': 100, 'B': 200, 'C': 300}

In [103]:
z1=pd.Series(dict1)
z1

A    100
B    200
C    300
dtype: int64

In [104]:
z2 = pd.Series([10,20,30,40],'A B C D '.split())
z2

A    10
B    20
C    30
D    40
dtype: int64

In [105]:
z1+z2

A    110.0
B    220.0
C    330.0
D      NaN
dtype: float64

# Slicing in Series

In [106]:
z2[0:2]

A    10
B    20
dtype: int64

In [107]:
z2['A':'C']

A    10
B    20
C    30
dtype: int64

# .loc and .iloc

In [108]:
z2.loc['A':'C']

A    10
B    20
C    30
dtype: int64

In [110]:
z2.iloc[0:3]

A    10
B    20
C    30
dtype: int64

In [111]:
z=pd.Series({100:'a',200:'b',300:'c'})
z

100    a
200    b
300    c
dtype: object

In [112]:
z[0]

KeyError: 0

In [113]:
z.iloc[0]

'a'

# Operation

In [114]:
z1

A    100
B    200
C    300
dtype: int64

In [115]:
z1>100

A    False
B     True
C     True
dtype: bool

In [116]:
z1<200

A     True
B    False
C    False
dtype: bool

# Broadcasting

In [117]:
z1+300

A    400
B    500
C    600
dtype: int64

# ordering 

In [118]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [119]:
z2.sort_values(ascending=False)

D    40
C    30
B    20
A    10
dtype: int64

In [120]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [123]:
z2.sort_values(ascending=False ,inplace=True)


In [124]:
z2

D    40
C    30
B    20
A    10
dtype: int64

# Aggregation on Series

In [125]:
z2

D    40
C    30
B    20
A    10
dtype: int64

In [126]:
z2.min()

10

In [127]:
z2.max()

40

In [129]:
z2.idxmax()

'D'

# DataFrame

In [130]:
rand_mat = np.random.randn(5,4)

In [131]:
rand_mat

array([[ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016],
       [ 0.32227152,  0.06034293, -1.04345   , -1.00994188],
       [ 0.44173637,  1.12887685, -1.83806777, -0.93876863],
       [-0.20184052,  1.04537128,  0.53816197,  0.81211867]])

In [132]:
df = pd.DataFrame(data=rand_mat,index='A B C D E'.split(),columns='W X Y Z'.split())


In [133]:
df

W         X         Y         Z
A  0.701672 -1.051082 -0.367548 -1.137460
B -1.322148  1.772258 -0.347459  0.670140
C  0.322272  0.060343 -1.043450 -1.009942
D  0.441736  1.128877 -1.838068 -0.938769
E -0.201841  1.045371  0.538162  0.812119

In [134]:
type(df)

pandas.core.frame.DataFrame

In [136]:
df['W']

A    0.701672
B   -1.322148
C    0.322272
D    0.441736
E   -0.201841
Name: W, dtype: float64

In [137]:
type(df['W'])

pandas.core.series.Series

# Selection and Indexing 

In [138]:
df.loc['A']

W    0.701672
X   -1.051082
Y   -0.367548
Z   -1.137460
Name: A, dtype: float64

In [139]:
df[['W','Z']]

W         Z
A  0.701672 -1.137460
B -1.322148  0.670140
C  0.322272 -1.009942
D  0.441736 -0.938769
E -0.201841  0.812119

# Add a new column

In [141]:
df['New'] = df['W'] + df['Z']

In [142]:
df

W         X         Y         Z       New
A  0.701672 -1.051082 -0.367548 -1.137460 -0.435788
B -1.322148  1.772258 -0.347459  0.670140 -0.652007
C  0.322272  0.060343 -1.043450 -1.009942 -0.687670
D  0.441736  1.128877 -1.838068 -0.938769 -0.497032
E -0.201841  1.045371  0.538162  0.812119  0.610278

In [143]:
df.drop('New',axis = 1)

W         X         Y         Z
A  0.701672 -1.051082 -0.367548 -1.137460
B -1.322148  1.772258 -0.347459  0.670140
C  0.322272  0.060343 -1.043450 -1.009942
D  0.441736  1.128877 -1.838068 -0.938769
E -0.201841  1.045371  0.538162  0.812119

In [144]:
df

W         X         Y         Z       New
A  0.701672 -1.051082 -0.367548 -1.137460 -0.435788
B -1.322148  1.772258 -0.347459  0.670140 -0.652007
C  0.322272  0.060343 -1.043450 -1.009942 -0.687670
D  0.441736  1.128877 -1.838068 -0.938769 -0.497032
E -0.201841  1.045371  0.538162  0.812119  0.610278

In [145]:
df.drop('New',axis = 1,inplace=True)

In [146]:
df

W         X         Y         Z
A  0.701672 -1.051082 -0.367548 -1.137460
B -1.322148  1.772258 -0.347459  0.670140
C  0.322272  0.060343 -1.043450 -1.009942
D  0.441736  1.128877 -1.838068 -0.938769
E -0.201841  1.045371  0.538162  0.812119

# Add a new Row

In [147]:
df.loc['F'] = df.loc['A']+df.loc['C']

In [148]:
df

W         X         Y         Z
A  0.701672 -1.051082 -0.367548 -1.137460
B -1.322148  1.772258 -0.347459  0.670140
C  0.322272  0.060343 -1.043450 -1.009942
D  0.441736  1.128877 -1.838068 -0.938769
E -0.201841  1.045371  0.538162  0.812119
F  1.023943 -0.990739 -1.410998 -2.147402

In [149]:
df.drop('F',axis=0,inplace=True)

In [150]:
df

W         X         Y         Z
A  0.701672 -1.051082 -0.367548 -1.137460
B -1.322148  1.772258 -0.347459  0.670140
C  0.322272  0.060343 -1.043450 -1.009942
D  0.441736  1.128877 -1.838068 -0.938769
E -0.201841  1.045371  0.538162  0.812119

In [151]:
df['X']['C']

0.060342934170488124

In [152]:
df.loc['C']['X']

0.060342934170488124

# Data Input and Output

In [157]:
pd.read_csv('example.csv.csv')

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2021                     Level 1                99999   
1      2021                     Level 1                99999   
2      2021                     Level 1                99999   
3      2021                     Level 1                99999   
4      2021                     Level 1                99999   
...     ...                         ...                  ...   
41710  2013                     Level 3                 ZZ11   
41711  2013                     Level 3                 ZZ11   
41712  2013                     Level 3                 ZZ11   
41713  2013                     Level 3                 ZZ11   
41714  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                  All industries  Dollars (millions)           H05   
3                  All industries  Dollars (millions)           H07   
4                  All industries  Dollars (millions)           H08   
...                           ...                 ...           ...   
41710  Food product manufacturing          Percentage           H37   
41711  Food product manufacturing          Percentage           H38   
41712  Food product manufacturing          Percentage           H39   
41713  Food product manufacturing          Percentage           H40   
41714  Food product manufacturing          Percentage           H41   

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance   
1      Sales, government funding, grants and subsidies  Financial performance   
2                    Interest, dividends and donations  Financial performance   
3                                 Non-operating income  Financial performance   
4                                    Total expenditure  Financial performance   
...                                                ...                    ...   
41710                                      Quick ratio       Financial ratios   
41711              Margin on sales of goods for resale       Financial ratios   
41712                                 Return on equity       Financial ratios   
41713                           Return on total assets       Financial ratios   
41714                            Liabilities structure       Financial ratios   

         Value                             Industry_code_ANZSIC06  
0      757,504  ANZSIC06 divisions A-S (excluding classes K633...  
1      674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2       49,593  ANZSIC06 divisions A-S (excluding classes K633...  
3       33,020  ANZSIC06 divisions A-S (excluding classes K633...  
4      654,404  ANZSIC06 divisions A-S (excluding classes K633...  
...        ...                                                ...  
41710       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41711       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41712       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41713        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41714       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[41715 rows x 10 columns]

In [154]:
pwd

'C:\\Users\\studio'

# Statistics function

In [158]:
x = np.array([[1,2,3],[4,5,6],[90,80,100]])

In [159]:
x

array([[  1,   2,   3],
       [  4,   5,   6],
       [ 90,  80, 100]])

In [160]:
np.amin(x)

1

In [161]:
np.amax(x)

100

In [162]:
np.amin(x,axis=1)

array([ 1,  4, 80])

In [163]:
np.amin(x,axis=0)

array([1, 2, 3])

In [164]:
np.amax(x,axis=0)

array([ 90,  80, 100])

In [165]:
np.amax(x,axis=1)

array([  3,   6, 100])

In [166]:
x

array([[  1,   2,   3],
       [  4,   5,   6],
       [ 90,  80, 100]])

In [167]:
np.average(x)

32.333333333333336

# weighted average

In [168]:
w = [1,2,3]

In [170]:
np.average(x,weights=w,axis = 0)

array([46.5, 42. , 52.5])

In [171]:
np.average(x,weights=w,axis = 1)

array([ 2.33333333,  5.33333333, 91.66666667])

In [172]:
np.mean(x)

32.333333333333336

In [173]:
np.mean(x[0])

2.0

In [174]:
np.mean(x[1])

5.0

In [176]:
np.mean(x[2])

90.0

In [177]:
np.mean(x , axis=0)

array([31.66666667, 29.        , 36.33333333])

In [178]:
np.mean(x , axis=1)

array([ 2.,  5., 90.])

In [179]:
np.median(x)

5.0

In [180]:
np.median(x , axis=0)

array([4., 5., 6.])

In [181]:
np.median(x , axis=1)

array([ 2.,  5., 90.])

In [182]:
np.var(x)

1686.888888888889

In [183]:
np.std(x)

41.071752931776466