In [1]:
pwd

'C:\\Users\\iibm'

In [2]:
print("WORKSHOP ON PYTHON")

WORKSHOP ON PYTHON


In [3]:
print('zhi')

zhi


In [5]:
print('a \'a\'')

a 'a'


In [7]:
print('''a 'alok' ''')

a 'alok' 


In [8]:
print('''
data
science
zhi

''')


data
science
zhi




###arithmetic operator

plus

# plus

In [9]:
2+5

7

In [10]:
2*5

10

In [11]:
2**2

4

In [12]:
4/2

2.0

In [13]:
4//2

2

In [14]:
4.2//2

2.0

In [15]:
2e2

200.0

In [16]:
2e8

200000000.0

In [17]:
x=10
x

10

In [18]:
print(x
    )

10


In [19]:
type(x)

int

In [20]:
print(type(x))

<class 'int'>


In [21]:
s= 'workshop'

In [22]:
s

'workshop'

slicing and indexing

s[start:end:step]

In [23]:
s[:5]

'works'

In [24]:
s[3:]

'kshop'

In [25]:
s[: :2]

'wrso'

In [26]:
pwd

'C:\\Users\\iibm'

In [27]:
'data'.split()

['data']

In [28]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [29]:
s.split()

['workshop']

In [30]:
s.split('S')

['workshop']

In [31]:
s.split('s')

['work', 'hop']

In [32]:
name='virat'
run=100

In [33]:
print(name + str(run))

virat100


In [37]:
print('this is a %s pen' %('ram'))

this is a ram pen


In [38]:
print('this is a %s pen %s' %('ram', 'abc'))

this is a ram pen abc


my_list=[]

In [40]:
my_list='A B C D' .split()

In [41]:
my_list

['A', 'B', 'C', 'D']

In [42]:
mylist=['a' ,5, 5.3]

In [43]:
mylist

['a', 5, 5.3]

In [44]:
type(mylist)

list

In [45]:
print(type(mylist))

<class 'list'>


# Slicing and Indexing

In [46]:
mylist[1]

5

In [47]:
mylist[0:2]

['a', 5]

In [48]:
mylist[0:3:1]

['a', 5, 5.3]

In [49]:
mylist[0:3:2]

['a', 5.3]

In [50]:
mylist*2

['a', 5, 5.3, 'a', 5, 5.3]

In [51]:
mylist=mylist + 'a'

TypeError: can only concatenate list (not "str") to list

In [52]:
mylist=mylist + ['a']

In [53]:
mylist

['a', 5, 5.3, 'a']

## LIST METHOD

In [54]:
l=[1,2,3,4,5]

In [55]:
l

[1, 2, 3, 4, 5]

In [56]:
l.append('A B C'.split())

In [57]:
l

[1, 2, 3, 4, 5, ['A', 'B', 'C']]

In [58]:
l=l.append('A')

In [59]:
print(l)

None


In [60]:
list= [1,2,3,4,5]

In [61]:
list

[1, 2, 3, 4, 5]

In [62]:
print(list)

[1, 2, 3, 4, 5]


In [63]:
print(type(list))

<class 'list'>


In [66]:
list.append('a')

In [68]:
list

[1, 2, 3, 4, 5, 'a', 'a']

In [69]:
list.pop(1)

2

In [70]:
list1

NameError: name 'list1' is not defined

In [72]:
l1=[1,2,3]
l2=[4,5,6]
l3=[6,7,8]

In [73]:
matrix=[l1,l2,l3]

In [74]:
matrix

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [75]:
type(matrix)

list

In [76]:
matrix[1][0]

4

In [78]:
matrix[2][1]

7

In [79]:
matrix[0][2]

3

In [77]:
len(matrix)

3

## Tuple

In [80]:
t1=(1,2,3)

In [81]:
t1

(1, 2, 3)

In [82]:
type(t1)

tuple

In [83]:
print(type(t1))

<class 'tuple'>


In [84]:
t1

(1, 2, 3)

In [85]:
t1[2]

3

In [86]:
l2=[1,2,3]

In [87]:
l2[2]=5

In [88]:
l2

[1, 2, 5]

In [89]:
t1[1]

2

In [90]:
t1[-1]

3

## Tuple Method

In [91]:
t1.index(2)

1

In [92]:
t1.count(3)

1

## Dictionary

In [93]:
disc1={1:'a',2:'b',3:'c'}

In [94]:
disc1

{1: 'a', 2: 'b', 3: 'c'}

In [95]:
type(disc1)

dict

In [96]:
print(type(disc1))

<class 'dict'>


In [97]:
disc1[1]

'a'

In [98]:
disc1[2]

'b'

In [99]:
disc1[4]='ram'

In [100]:
disc1

{1: 'a', 2: 'b', 3: 'c', 4: 'ram'}

## Nested Dictionary

In [101]:
disc1={1:'a',2:'b','key1':{1:'a',2:'hello',3:'c'},3:'c'}

In [102]:
disc1

{1: 'a', 2: 'b', 'key1': {1: 'a', 2: 'hello', 3: 'c'}, 3: 'c'}

In [103]:
disc1['key1'][2][2]

'l'

In [104]:
disc1['key1'][2]

'hello'

## METHOD

In [105]:
disc1.keys()

dict_keys([1, 2, 'key1', 3])

In [106]:
disc1.values()

dict_values(['a', 'b', {1: 'a', 2: 'hello', 3: 'c'}, 'c'])

In [107]:
disc1.items()

dict_items([(1, 'a'), (2, 'b'), ('key1', {1: 'a', 2: 'hello', 3: 'c'}), (3, 'c')])

# SET

###### unordered collection

In [108]:
x=set()

In [109]:
x

set()

In [110]:
type(x)

set

In [111]:
print(type(x))

<class 'set'>


In [112]:
x.add(1)

In [113]:
x

{1}

In [114]:
x.add(1,2,3,4,5)

TypeError: add() takes exactly one argument (5 given)

In [115]:
list2=[1,2,3,1,2,3,2,2,3,4]

In [116]:
list2

[1, 2, 3, 1, 2, 3, 2, 2, 3, 4]

In [117]:
set(list2)

{1, 2, 3, 4}

## Boolean

In [118]:
True

True

In [119]:
False

False

In [120]:
None

In [129]:
list3= [1,2,[3,4,'hello']]

In [130]:
list3[2][2]=['goodbye']
list3

[1, 2, [3, 4, ['goodbye']]]

In [131]:
list5 = [1,2,2,33,4,4,11,22,3,3,2]
x = set(list5)
x

{1, 2, 3, 4, 11, 22, 33}

## Membership Operator

In [132]:
m='zhipatna'

In [133]:
m

'zhipatna'

In [134]:
'p' in m

True

In [135]:
't' not in m

False

In [136]:
x=100

In [137]:
y=100

In [138]:
x is y

True

In [139]:
x is not y

False

In [140]:
list1=[1,2,3]

In [141]:
list2=[1,2,3]

In [145]:
list1 == list2

True

## Numerical Python

In [146]:
import numpy as np

In [147]:
x = [1,2,3,4,5]

In [148]:
x

[1, 2, 3, 4, 5]

In [149]:
type(x)

list

In [150]:
y = np.array(x)

In [151]:
type(y)

numpy.ndarray

In [152]:
x2 = (1,2,3,'NIELIT',3.4)

In [153]:
np.array(x2)

array(['1', '2', '3', 'NIELIT', '3.4'], dtype='<U11')

## Linespace

In [155]:
np.linspace(start=0, stop=20, num=10,endpoint=False,retstep=True)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0)

In [156]:
np.linspace(start=0, stop=20, num=10,endpoint=True,retstep=True)

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

## Arange

In [157]:
np.arange(start=0,stop=50,step=5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [158]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [159]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [160]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

## Create 3*3 Array

In [162]:
z = [[1,2,3],[4,5,6],[7,8,9]]

In [163]:
z

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [164]:
y = np.array(z)

In [165]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [168]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [169]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Reshaping

In [170]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [171]:
x #1*10 type

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Convert to 5*2

In [172]:
x.reshape((5,2))

ValueError: cannot reshape array of size 9 into shape (5,2)

## Slicing

In [173]:
a = np.arange(10)

In [174]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
s = slice(2,7)

In [176]:
a[s]

array([2, 3, 4, 5, 6])

In [177]:
s1 = slice(2,7,2)

In [178]:
a[s1]

array([2, 4, 6])

In [179]:
a[2:7]

array([2, 3, 4, 5, 6])

In [180]:
a[2:7:2]

array([2, 4, 6])

## Random Number Generation

In [181]:
np.random.rand(5)

array([0.85521218, 0.82094499, 0.5806782 , 0.50346513, 0.51470062])

In [182]:
np.random.rand(5)

array([0.78938545, 0.85286307, 0.37630441, 0.45164639, 0.63539441])

## Normal Distribution

In [183]:
np.random.randn(5,4)

array([[ 0.28578724, -0.45757383, -1.83828685,  0.15758961],
       [ 1.28213566,  1.13852743,  0.47546792, -1.82771346],
       [-0.20777516,  0.74761411,  1.05241819,  0.20391169],
       [-0.25546115,  1.00908724,  0.50650832,  0.11867628],
       [ 1.18415859,  1.84796097,  0.28317287, -0.47960087]])

### Randint

In [184]:
np.random.randint(low=0,high=100)

18

In [185]:
# 4 digit Random Number
np.random.randint(low=1000,high=9999)

6646

## Seed

In [186]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [187]:
np.random.seed(23)
np.random.randint(low=1000,high=9999)

9787